### ISSUE TITLE
Using the "Multiple Frame" feature HELP

### ISSUE THREAD

**Issue by jay-tailor** [kinectron/kinectron#10]
Having some trouble with the Multiple Frames function on Kinectron.exe

When trying to use the multiple frame feature, what do we put inside the boxes to establish a Peer Id. Currently we have two computers with a kinect each on the same LAN. 

What would we enter for peer DI and Server Details? How do we find what our ID is to use? 
Thanks in advance 

![capture](https://user-images.githubusercontent.com/36112876/40926365-0835f2ac-67ea-11e8-829c-9665dba72f27.PNG)

**Comment by lisajamhoury** [comment]
Closing this now. Reopen if you have other questions.
