### ISSUE TITLE
Error resolving paths in Macbook's Bootcamp

### ISSUE THREAD

**Issue by Jagni** [kinectron/kinectron#15]
```
Uncaught Error: The specified module could not be found.
\\?\C:\kinectron-server-0.0.5.1\resources\app\node_modules\kinect2\build\Release\kinect2.node
```

I'm using the preview release 0.0.5.1 and got this error after starting kinectron-server.exe

I've got a Windows 10 dual boot in a MacBook Pro Mid 2014 using Bootcamp.

**Comment by lisajamhoury** [comment]
See #7 

Does that help?

**Comment by Jagni** [comment]
Unfortunately no...

I've deleted the directory, re-downloaded [the file](https://github.com/kinectron/kinectron/releases/download/0.0.5.1/kinectron-server-0.0.5.1.zip) and unzipped it in C:\

But I'm still going through the same error

**Comment by Jagni** [comment]
Okay, it turns out that I only had kinect SDK 1.0 and 1.8 installed. Installing 2.0 solved it!
Sorry for the mistake

**Comment by lisajamhoury** [comment]
Great!

**Comment by pesinasiller** [comment]
any updates on this? i have a similar problem
I have a Windows 10 dual boot in a MacBook Pro Mid 2014 using Bootcamp and kinect SDK 2.0

Uncaught Error: The specified module could not be found.
\\?\C:\kinectron-server-win32-x64\resources\app\node_modules\kinect-azure\build\Release\kinectAzure.node

**Comment by lisajamhoury** [comment]
Which release of the server are you using? Where are you seeing this error -- Is it in electron console on open? Are you planning to use the Kinect v2 or the Azure Kinect? 

I haven't personally tested on bootcamp, but I know people have used Kinectron successfully on bootcamp, so hopefully we can figure it out.

**Comment by pesinasiller** [comment]
I'm trying to use release 0.3.3 and kinect 2. Yes, the error is showing in the electron console on open. I searched the file mentioned and it is there, in that path.
