### ISSUE TITLE
new architecture for releases

### ISSUE THREAD

**Issue by montoyamoraga** [kinectron/kinectron#19]
kinectron.bundle.js should be kinectron_client.js or kinectron-client.js

for every release there should be a zip file with the client and a zip file with the server.

**Comment by lisajamhoury** [comment]
I've changed the file name to kinectron-client.js and it the client file is now hosted on jsdelivr with a matching tag to the current release. For example: 

The new release is available at https://github.com/kinectron/kinectron/releases/tag/0.2.0 and the client is at: https://cdn.jsdelivr.net/gh/kinectron/kinectron@0.2.0/client/dist/kinectron-client.js
