### ISSUE TITLE
add console.log() to the client to signal when it loads successfully

### ISSUE THREAD

**Issue by montoyamoraga** [kinectron/kinectron#20]

**Comment by lisajamhoury** [comment]
@montoyamoraga Do we have the code or more notes for this anywhere? I vaguely remember what this was about, but I know I wrote code in an example for this. Can't remember what it was

**Comment by montoyamoraga** [comment]
@lisajamhoury I don't remember an example using it
I mentioned because when you load Tone.js, it prints in the console a success message
and I like that

**Comment by lisajamhoury** [comment]
Closing this because it's similar to #28
