### ISSUE TITLE
Not able to develop the server

### ISSUE THREAD

**Issue by montoyamoraga** [kinectron/kinectron#25]
I installed everything

Ran into some trouble because of multiple Python distributions in my computer and had to 
make npm and node-gyp point to Python 2.7

Ran into some trouble with Visual Studio, I had installed Visual Studio Community 2017 and had to uninstall and go back to Visual Studio 2015 because of node-gyp.

**Comment by lisajamhoury** [comment]
I've updated [the install instructions](https://github.com/kinectron/kinectron/blob/master/CONTRIBUTE.md#contribute-to-server-application) based on a new install on a fresh Windows 10 install. Steps 1-3 are for building the server for development. 

Closing this for now, but please re-open if this doesn't work for you. 

See commit for more details. https://github.com/kinectron/kinectron/commit/d19b81d1517006ce59a9c99afc047dfc30dca0b8
