### ISSUE TITLE
Add version message to client-side api

### ISSUE THREAD

**Issue by lisajamhoury** [kinectron/kinectron#28]
What is the proper way to version the client library? I add version numbers when I create new releases of the server, but there's currently no way to know which client library file is the most up to date.

**Comment by montoyamoraga** [comment]
I say we make them match, what do you think?

**Comment by lisajamhoury** [comment]
@montoyamoraga It wouldn't work to match them since I develop them at different times

**Comment by montoyamoraga** [comment]
oh i see, so then different numbers should be fine

**Comment by lisajamhoury** [comment]
ok. do you know of any good examples. ie how this should be noted in the
file? i can look it up, just thought you might already have good examples.

**Comment by montoyamoraga** [comment]
I want kinectron-clien.js to console.log on the terminal when it's loaded,
including the version number, just like Tone.js does it.
You can see an example here, when you open the console
[Tone.js example](https://tonejs.github.io/examples/#envelope)

Also, the file should be minified for using Pierre's solution for CDN

**Comment by lisajamhoury** [comment]
Create a success message on load as part of the logged message as well.

**Comment by lisajamhoury** [comment]
This is included in version 0.3.0
