### ISSUE TITLE
How to use Peer ID to get Kinect Joint Data

### ISSUE THREAD

**Issue by RinayShah** [kinectron/kinectron#30]
I want to use the Peer ID to get the kinect joint data is that possible and if so how can it be done?
![untitled3](https://user-images.githubusercontent.com/30274343/42767737-cb0f3ba4-88eb-11e8-8501-5ccbf0148dd9.jpg)
![untitled4](https://user-images.githubusercontent.com/30274343/42767751-d3dde334-88eb-11e8-9d47-3d2f903487b1.jpg)

**Comment by lisajamhoury** [comment]
The joint data is passed in as an argument in the callback that you set when you start tracked bodies. So in your case, the joint data is a property on "body" at line 56, the funtion bodyTracked. The 26 joints of the Kinect skeleton are in body.joints. See #12 for more info on joints.

**Comment by lisajamhoury** [comment]
Closing this, but you can reopen if you have a more specific question.
