### ISSUE TITLE
How to get Kinect Joint Data without using Chrome's Console 

### ISSUE THREAD

**Issue by RinayShah** [kinectron/kinectron#31]
I am using the Client-side Kinectron API and was wondering if there is a way to see there is a way to see the kinect joint data wihtout using Chrome's console? Also if there is a way to see the position of each indivual joint ex. Head (x,y,z) Neck (x,y,z)? And is there a way to use the Peer ID in C# to display the joint data?

![untitled5](https://user-images.githubusercontent.com/30274343/42768986-eee97ec4-88ee-11e8-9960-7bb1065701aa.png)

**Comment by lisajamhoury** [comment]
The way to see the data within the objects is in the console. See #14 for discussion on Kinectron and C#
