### ISSUE TITLE
Get Joint Name and its x,y,z position 

### ISSUE THREAD

**Issue by RinayShah** [kinectron/kinectron#34]
Hey, when I do console.log(joint) I only see depth, color, camera position however I want the object to display JSON objects like:
Name: Head
x=-0.2126
y=0.523
z=0.2323

Currently, it's like this:

![42768986-eee97ec4-88ee-11e8-9960-7bb1065701aa](https://user-images.githubusercontent.com/30274343/43092157-3e0aefa2-8e7a-11e8-9166-e027b8c804bd.png)

But I want it like (different code):

![untitled](https://user-images.githubusercontent.com/30274343/43092163-444d391a-8e7a-11e8-93b2-38f4085548c7.png)

**Comment by lisajamhoury** [comment]
You're best bet would be to log the full body object so that you can see the array of joints rather than just logging the joint itself.
