### ISSUE TITLE
kinectron = new Kinectron(); Error

### ISSUE THREAD

**Issue by ladynobeard** [kinectron/kinectron#38]
I'm a total newbie with Kinect. When there's no IP in the argument I get an error in the console: 

Failed to load resource: net::ERR_CONNECTION_REFUSED

I'm not sure what happened?

**Comment by lisajamhoury** [comment]
Can you post your code—just those relevant lines of code is good—and a
screenshot of the error.

**Comment by ladynobeard** [comment]
It was my bad! I figured out I forgot to turn on the kinectron.

**Comment by lisajamhoury** [comment]
Ok cool!
