### ISSUE TITLE
three.js

### ISSUE THREAD

**Issue by profjere** [kinectron/kinectron#41]
I'm thinking of working in three.js, rather than the more common (for this project) p5.js.  Just wondering if there was any demo three.js files?

Thanks.

**Comment by lisajamhoury** [comment]
Yes there are three.js examples here https://github.com/kinectron/kinectron/tree/master/examples/threejs_examples

There is also a plugin specifically for the RGBD feed in three.js. But the RGBD feed is low quality in the current release of Kinectron.  
https://github.com/kinectron/Three-Kinectron
