### ISSUE TITLE
Create New Example -- Azure record

### ISSUE THREAD

**Issue by lisajamhoury** [kinectron/kinectron#64]
I added a new example to illustrate how to record on client with Kinect Azure. 

@montoyamoraga If you have a moment, would appreciate your review!
https://github.com/kinectron/kinectron/tree/master/examples/azure_examples/p5_examples/record

Thanks!
Lisa

**Comment by montoyamoraga** [comment]
it looks great to me, i read it and i love how commented it is, 
we are now  having a more consistent and very documented style of the examples,
super readable :)

**Comment by lisajamhoury** [comment]
Awesome. Thanks for checking :)
