### ISSUE TITLE
Fails to start

### ISSUE THREAD

**Issue by tp** [kinectron/kinectron#7]
Hi,

I just wanted to try it Kinectron on a fresh Window 10 Pro 64bit installation, but it fails with a node error: Module not found.

Does anybody have any idea what could be causing this or how to work around it?

Thanks

<img width="1323" alt="fad7a4c5-44c1-44d8-9cc1-704c73228ec5" src="https://user-images.githubusercontent.com/52437/40270648-63e0798e-5b91-11e8-9453-1fd253087364.png">

**Comment by lisajamhoury** [comment]
I've seen this happen before when the app unpacks incorrectly. Try deleting the folder and re-downloading [the application](https://github.com/kinectron/kinectron/releases/tag/0.0.5.0). Make sure that you unzip it in the c:/ level to avoid issues with file name length in Windows.

**Comment by tp** [comment]
Yeah, furthermore this was running in a VM that only supported DX10, so Kinect would've not worked anyway.

Kinectron works fine when running on bare-metal.

So, I'll be closing this.
