### ISSUE TITLE
How to draw depth image to canvas?

### ISSUE THREAD

**Issue by playdscription** [kinectron/kinectron#70]
Can anyone help with an example of how to simply draw the depth image to the screen? It seems its much easier in Java using  getDepthImage(). I cant figure out how to do it in p5.js.

**Comment by lisajamhoury** [comment]
Here are basic examples for drawing the camera feeds from the Kinect in p5. 

[Windows Kinect](https://github.com/kinectron/kinectron/blob/master/examples/windows_examples/p5_examples/gettingstarted/sketch.js)
[Azure Kinect](https://github.com/kinectron/kinectron/blob/master/examples/azure_examples/p5_examples/gettingstarted/sketch.js)

**Comment by lisajamhoury** [comment]
Closing this issue, but feel free to reopen if you need additional guidance.
