### ISSUE TITLE
p5 record example does not record

### ISSUE THREAD

**Issue by aaronsantiago** [kinectron/kinectron#72]
https://github.com/kinectron/kinectron/tree/master/examples/windows_examples/p5_examples/record

When run, it logs "Record does not work until a feed is started" into the console when either up or down is pressed, even when the multiframe is running.

Tested with #71, Kinect v2. Client was running Firefox on a Macbook Pro.

**Comment by lisajamhoury** [comment]
This is fixed in the new release 0.3.3. As of 0.3.2 you have to set the Kinect type to 'azure' or 'windows'. Adding this fixed the error. [Fixed with this commit](https://github.com/kinectron/kinectron/commit/92c6196f1fcafa645dd6eec0432790e09629f8f9). 
 
```
// Set kinect type to windows
kinectron.setKinectType('windows');
```
