### ISSUE TITLE
RTCIceServer.url is deprecated! Use urls instead.

### ISSUE THREAD

**Issue by proxycase** [kinectron/kinectron#9]
Sorry I would submit a pull request but I'm still learning this stuff.
Can be fixed in the kinectron.bundle.js on line 1044 change:

`var defaultConfig = {'iceServers': [{ 'url': 'stun:stun.l.google.com:19302' }]};`
to
`var defaultConfig = {'iceServers': [{ 'urls': 'stun:stun.l.google.com:19302' }]};`

**Comment by lisajamhoury** [comment]
Thanks for reporting this! It is fixed as of release 0.2.0. 

The new release is available at https://github.com/kinectron/kinectron/releases/tag/0.2.0 and the client is at:

https://cdn.jsdelivr.net/gh/kinectron/kinectron@0.2.0/client/dist/kinectron-client.js
